FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ingestor ./cmd/ingestor

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/ingestor .
RUN mkdir -p /app/public/openapi
COPY public/logtopus.png /app/public/
COPY public/openapi/openapi.html /app/public/openapi/
COPY public/openapi/openapi.ingestor.yaml /app/public/openapi/
COPY public/openapi/openapi.base.yaml /app/public/openapi/

EXPOSE 8080
CMD ["./ingestor"]
