FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o query-service ./cmd/query-service

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/query-service .
COPY openapi.query.yaml .

EXPOSE 8081
CMD ["./query-service"]
