FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ingestor ./cmd/ingestor

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/ingestor .
COPY openapi.ingestor.yaml .

EXPOSE 8080
CMD ["./ingestor"]
