FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o query-service ./cmd/query-service

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/query-service .
RUN mkdir -p /app/public/openapi
COPY public/logtopus.png /app/public/
COPY public/openapi/openapi.query.yaml /app/public/openapi/
COPY public/openapi/openapi.base.yaml /app/public/openapi/

EXPOSE 8081
CMD ["./query-service"]
